package com.cinema.ticket_booking.config;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.jdbc.core.JdbcTemplate;

/**
 * Temporary config to fix NULL version columns for existing records.
 * This can be deleted after the first successful run.
 */
@Configuration
@RequiredArgsConstructor
@Slf4j
public class SchemaFixConfig {

    private final JdbcTemplate jdbcTemplate;

    @Bean
    public CommandLineRunner fixNullVersions() {
        return args -> {
            log.info("[SchemaFix] Checking for data integrity issues...");

            // 1. Fix NULL versions and numeric columns (Existing logic)
            jdbcTemplate.execute("UPDATE users SET version = 0 WHERE version IS NULL");
            jdbcTemplate.execute("UPDATE users SET reward_points = 0 WHERE reward_points IS NULL");
            jdbcTemplate.execute("UPDATE users SET available_exp = 0 WHERE available_exp IS NULL");
            jdbcTemplate.execute("UPDATE users SET membership_tier = 'BRONZE' WHERE membership_tier IS NULL");
            jdbcTemplate.execute("UPDATE bookings SET version = 0 WHERE version IS NULL");
            jdbcTemplate.execute("UPDATE screens SET is_deleted = false WHERE is_deleted IS NULL");
            jdbcTemplate.execute("UPDATE promotions SET is_active = true WHERE is_active IS NULL");
            jdbcTemplate.execute("UPDATE promotions SET start_date = CURRENT_TIMESTAMP - INTERVAL '1 day' WHERE start_date IS NULL OR start_date > CURRENT_TIMESTAMP");
            jdbcTemplate.execute("UPDATE promotions SET end_date = CURRENT_TIMESTAMP + INTERVAL '30 days' WHERE end_date IS NULL OR end_date < CURRENT_TIMESTAMP");
            jdbcTemplate.execute("UPDATE vouchers SET is_active = true WHERE is_active IS NULL");
            jdbcTemplate.execute("UPDATE vouchers SET valid_to = CURRENT_TIMESTAMP + INTERVAL '90 days' WHERE valid_to IS NULL OR valid_to < CURRENT_TIMESTAMP");

            // 2. Programmatic Migration for 'seats' table Grid columns
            // We do this because ddl-auto=update fails to add NOT NULL columns to existing
            // data
            try {
                log.info("[SchemaFix] Ensuring 'seats' table has grid columns...");

                // Add columns as NULLABLE first
                jdbcTemplate.execute("ALTER TABLE seats ADD COLUMN IF NOT EXISTS grid_row INT");
                jdbcTemplate.execute("ALTER TABLE seats ADD COLUMN IF NOT EXISTS grid_col INT");
                jdbcTemplate.execute("ALTER TABLE seats ADD COLUMN IF NOT EXISTS seat_label VARCHAR(10)");

                // Migrate data for existing records
                int migrated = jdbcTemplate.update(
                        "UPDATE seats SET " +
                                "  grid_row = ASCII(row_label) - 65, " +
                                "  grid_col = col_number - 1, " +
                                "  seat_label = row_label || CAST(col_number AS TEXT) " +
                                "WHERE grid_row IS NULL OR grid_col IS NULL");

                if (migrated > 0) {
                    log.info("[SchemaFix] Migrated {} existing seats to grid layout", migrated);
                }

                // Now set NOT NULL (ignore if already set)
                jdbcTemplate.execute("ALTER TABLE seats ALTER COLUMN grid_row SET NOT NULL");
                jdbcTemplate.execute("ALTER TABLE seats ALTER COLUMN grid_col SET NOT NULL");
                jdbcTemplate.execute("ALTER TABLE seats ALTER COLUMN seat_label SET NOT NULL");

                // Add Unique Constraint if not exists
                try {
                    jdbcTemplate.execute(
                            "ALTER TABLE seats ADD CONSTRAINT uk_seat_screen_grid UNIQUE (screen_id, grid_row, grid_col)");
                    log.info("[SchemaFix] Created unique constraint uk_seat_screen_grid");
                } catch (Exception e) {
                    // Constraint likely already exists
                }

                // 3. Update pricing_rules check constraint for 'PROMOTION' type
                try {
                    log.info("[SchemaFix] Updating pricing_rules check constraint for 'PROMOTION'...");
                    // Drop the old constraint (PostgreSQL specific name usually generated by
                    // Hibernate)
                    jdbcTemplate.execute(
                            "ALTER TABLE pricing_rules DROP CONSTRAINT IF EXISTS pricing_rules_rule_type_check");

                    // Re-add with new enum value
                    jdbcTemplate.execute("ALTER TABLE pricing_rules ADD CONSTRAINT pricing_rules_rule_type_check " +
                            "CHECK (rule_type IN ('DAY_OF_WEEK', 'TIME_FRAME', 'DATE_RANGE', 'SEAT_TYPE', 'PROMOTION'))");
                    log.info("[SchemaFix] Successfully updated pricing_rules check constraint.");
                } catch (Exception e) {
                    log.warn("[SchemaFix] Could not update pricing_rules constraint: {}", e.getMessage());
                }

            } catch (Exception e) {
                log.error("[SchemaFix] Failed to migrate schema: {}", e.getMessage());
            }

            log.info("[SchemaFix] Data integrity check and migration completed.");
        };
    }
}
