sonar.organization=binhln115
sonar.projectKey=novaticket-ai
sonar.projectName=NovaTicket AI
sonar.host.url=https://sonarcloud.io
sonar.sources=app
sonar.exclusions=venv/**,tests/**,__pycache__/**,*.log,chroma_db/**,faiss_index/**,data/**,*.db,*.sqlite3,cleanmodel.txt,test_agent.py,scripts/**
sonar.python.version=3.10
sonar.coverage.exclusions=**/*


