sonar.organization=binhln115
sonar.projectKey=novaticket-frontend
sonar.projectName=NovaTicket Frontend
sonar.host.url=https://sonarcloud.io
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.test.js,src/**/*.test.jsx,src/**/*.test.ts,src/**/*.test.tsx,src/**/*.spec.js,src/**/*.spec.jsx,src/**/*.spec.ts,src/**/*.spec.tsx
sonar.exclusions=node_modules/**,dist/**,build/**,vite.config.js,eslint.config.js,postcss.config.js,tailwind.config.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/*
