# Bắt buộc load file .env ở local
spring.config.import=optional:classpath:.env[.properties]

# Logging & Debug (Chỉ bật ở Local để dễ dò bug)
spring.jpa.show-sql=true
logging.level.com.cinema=DEBUG
logging.level.org.springframework.security=WARN

# Mở cửa cho Swagger / OpenAPI để test API
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# URL VNPay (Dưới local thì dùng Sandbox)
vnpay.url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html