# Kế thừa việc load file .env ở local cho môi trường test local
spring.config.import=optional:classpath:.env[.properties]

# Logging & Debug (Bật ở test để dễ dò lỗi testcase Postman)
spring.jpa.show-sql=false
logging.level.com.cinema=DEBUG
logging.level.org.springframework.security=WARN

# Mở cửa cho Swagger / OpenAPI để test
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# URL VNPay
vnpay.url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html

# Mật khẩu test cho CommandLineRunner github actions
app.test.admin-password=${APP_TEST_ADMIN_PASSWORD:AdminPassword123!}
app.test.staff-password=${APP_TEST_STAFF_PASSWORD:StaffPassword123!}
app.test.customer-password=${APP_TEST_CUSTOMER_PASSWORD:CustomerPassword123!}


# Hibernate Batching
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true


